[project]
name = "cvdemo2026"
version = "0.1.0"
description = "Demo app for presentation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.0.0",
    "nest-asyncio>=1.6.0",
    "pandas>=3.0.0",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "streamlit>=1.54.0",
]
